apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: golang-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: go-webserver
          servicePort: 8080
